services:
  server:
    build: .
    container_name: SkullKing_server_app
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"

  client:
    build: .
    container_name: SkullKing_client_app
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"
